apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodebackend
  labels:
    app: nodebackend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodebackend
  template:
    metadata:
      labels:
        app: nodebackend
    spec:
      containers:
        - name: nodebackend
          image: 236661691969.dkr.ecr.us-east-2.amazonaws.com/test-node-app
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
